## Quick Linear Regression

In [3]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [4]:
x = np.array(range(0, 20))
y = x * (-3) + 10

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 10   7   4   1  -2  -5  -8 -11 -14 -17 -20 -23 -26 -29 -32 -35 -38 -41
 -44 -47]


In [5]:
x.shape, y.shape

((20,), (20,))

In [6]:
# 1. Session Clear
keras.backend.clear_session()

# 2. Model
model = keras.models.Sequential()

# 3. Model Block
model.add(keras.layers.Input(shape=(1,)))
model.add(keras.layers.Dense(1))

# 4. Compile
model.compile(loss='mse', optimizer='adam')

In [9]:
# 5. fit
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 0s 9ms/step - loss: 885.1752
Epoch 2/10
1/1 [==============================] - 0s 7ms/step - loss: 884.4910
Epoch 3/10
1/1 [==============================] - 0s 7ms/step - loss: 883.8073
Epoch 4/10
1/1 [==============================] - 0s 7ms/step - loss: 883.1239
Epoch 5/10
1/1 [==============================] - 0s 8ms/step - loss: 882.4409
Epoch 6/10
1/1 [==============================] - 0s 8ms/step - loss: 881.7584
Epoch 7/10
1/1 [==============================] - 0s 9ms/step - loss: 881.0764
Epoch 8/10
1/1 [==============================] - 0s 12ms/step - loss: 880.3947
Epoch 9/10
1/1 [==============================] - 0s 9ms/step - loss: 879.7134
Epoch 10/10
1/1 [==============================] - 0s 10ms/step - loss: 879.0325


In [10]:
# 6. Predict
model.predict(x).reshape(-1)

array([-0.1090351 ,  0.29334614,  0.69572735,  1.0981086 ,  1.5004898 ,
        1.902871  ,  2.3052526 ,  2.7076337 ,  3.110015  ,  3.512396  ,
        3.9147773 ,  4.3171587 ,  4.71954   ,  5.121921  ,  5.5243025 ,
        5.9266834 ,  6.329065  ,  6.7314463 ,  7.133827  ,  7.5362086 ],
      dtype=float32)

## Quick Logistic Regression

In [11]:
x = np.array(range(0, 20))
y = np.array([0]*10 + [1]*10)

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]


In [12]:
# 1. Session Clear
keras.backend.clear_session()

# 2. Model
model = keras.models.Sequential()

# 3. Model Block
model.add(keras.layers.Input(shape=(1,)))
model.add(keras.layers.Dense(1, activation='sigmoid'))

# 4. Compile
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [13]:
# 5. fit
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 1s 1s/step - loss: 0.6066 - accuracy: 0.5500
Epoch 2/10
1/1 [==============================] - 0s 9ms/step - loss: 0.6055 - accuracy: 0.5500
Epoch 3/10
1/1 [==============================] - 0s 7ms/step - loss: 0.6044 - accuracy: 0.5500
Epoch 4/10
1/1 [==============================] - 0s 7ms/step - loss: 0.6034 - accuracy: 0.5500
Epoch 5/10
1/1 [==============================] - 0s 7ms/step - loss: 0.6024 - accuracy: 0.5500
Epoch 6/10
1/1 [==============================] - 0s 6ms/step - loss: 0.6014 - accuracy: 0.5500
Epoch 7/10
1/1 [==============================] - 0s 7ms/step - loss: 0.6004 - accuracy: 0.5500
Epoch 8/10
1/1 [==============================] - 0s 7ms/step - loss: 0.5994 - accuracy: 0.5500
Epoch 9/10
1/1 [==============================] - 0s 7ms/step - loss: 0.5985 - accuracy: 0.5500
Epoch 10/10
1/1 [==============================] - 0s 10ms/step - loss: 0.5975 - accuracy: 0.5500


In [14]:
# 6. Predict
model.predict(x).reshape(-1)

array([0.49750423, 0.5309729 , 0.56416523, 0.59679234, 0.628585  ,
       0.6593019 , 0.6887363 , 0.71672046, 0.743127  , 0.7678693 ,
       0.7908989 , 0.81220263, 0.83179736, 0.8497259 , 0.86605126,
       0.8808517 , 0.89421654, 0.9062419 , 0.917027  , 0.92667186],
      dtype=float32)

In [15]:
print(y)

[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]
