## Quick Linear Regression

In [1]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [2]:
x = np.array(range(0, 20))
y = x * 2 - 1

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [3]:
# 1. Session Clear
keras.backend.clear_session()

# 2. Model
input_layer = keras.layers.Input(shape=(1,))
output_layer = keras.layers.Dense(1)(input_layer)

# 3. Model Block
model = keras.models.Model(inputs=input_layer, outputs=output_layer)

# 4. Compile
model.compile(loss='mse', optimizer='adam')

In [4]:
# 5. fit
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 2s 2s/step - loss: 48.7035
Epoch 2/10
1/1 [==============================] - 0s 7ms/step - loss: 48.5376
Epoch 3/10
1/1 [==============================] - 0s 7ms/step - loss: 48.3720
Epoch 4/10
1/1 [==============================] - 0s 6ms/step - loss: 48.2066
Epoch 5/10
1/1 [==============================] - 0s 7ms/step - loss: 48.0416
Epoch 6/10
1/1 [==============================] - 0s 6ms/step - loss: 47.8769
Epoch 7/10
1/1 [==============================] - 0s 6ms/step - loss: 47.7126
Epoch 8/10
1/1 [==============================] - 0s 6ms/step - loss: 47.5485
Epoch 9/10
1/1 [==============================] - 0s 6ms/step - loss: 47.3848
Epoch 10/10
1/1 [==============================] - 0s 6ms/step - loss: 47.2214


In [5]:
# 6. Predict
print(y)
print(model.predict(x).reshape(-1))

[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]
[9.9940114e-03 1.3168228e+00 2.6236515e+00 3.9304802e+00 5.2373090e+00
 6.5441375e+00 7.8509665e+00 9.1577950e+00 1.0464623e+01 1.1771452e+01
 1.3078280e+01 1.4385110e+01 1.5691938e+01 1.6998768e+01 1.8305597e+01
 1.9612425e+01 2.0919254e+01 2.2226084e+01 2.3532911e+01 2.4839741e+01]


## Quick Logistic Regrssion

In [6]:
x = np.array(range(0, 20))
y = np.array([0]*10 + [1]*10)

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]


In [7]:
# 1. Session Clear
keras.backend.clear_session()

# 2. Model
input_layer = keras.layers.Input(shape=(1,))
output_layer = keras.layers.Dense(1, activation='sigmoid')(input_layer)

# 3. Model Block
model = keras.models.Model(inputs=input_layer, outputs=output_layer)

# 4. Compile
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [8]:
# 5. fit
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 1s 974ms/step - loss: 2.3066 - accuracy: 0.5500
Epoch 2/10
1/1 [==============================] - 0s 6ms/step - loss: 2.3039 - accuracy: 0.5500
Epoch 3/10
1/1 [==============================] - 0s 6ms/step - loss: 2.3012 - accuracy: 0.5500
Epoch 4/10
1/1 [==============================] - 0s 7ms/step - loss: 2.2986 - accuracy: 0.5500
Epoch 5/10
1/1 [==============================] - 0s 5ms/step - loss: 2.2959 - accuracy: 0.5500
Epoch 6/10
1/1 [==============================] - 0s 6ms/step - loss: 2.2933 - accuracy: 0.5500
Epoch 7/10
1/1 [==============================] - 0s 6ms/step - loss: 2.2906 - accuracy: 0.5500
Epoch 8/10
1/1 [==============================] - 0s 6ms/step - loss: 2.2879 - accuracy: 0.5500
Epoch 9/10
1/1 [==============================] - 0s 6ms/step - loss: 2.2853 - accuracy: 0.5500
Epoch 10/10
1/1 [==============================] - 0s 7ms/step - loss: 2.2826 - accuracy: 0.5500


In [9]:
# 6. Predict
print(y)
print(model.predict(x).reshape(-1))

[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]
[0.49750012 0.7267519  0.877225   0.9504811  0.9809755  0.99283266
 0.99732    0.9990007  0.9996277  0.99986136 0.9999484  0.9999808
 0.99999285 0.9999974  0.99999905 0.99999964 0.9999999  1.
 1.         1.        ]
