# Multi-Class Classification

In [1]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

from sklearn.datasets import load_iris

In [2]:
iris = load_iris()

In [3]:
x = iris.data
y = iris.target

In [4]:
x.shape, y.shape

((150, 4), (150,))

In [5]:
# target 확인
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [6]:
# One-Hot Encoding
from tensorflow.keras.utils import to_categorical

In [7]:
y = to_categorical(y, 3)

In [8]:
x.shape, y.shape

((150, 4), (150, 3))

## 1. Sequential API Style

In [10]:
# 1. Session Clear
keras.backend.clear_session()

# 2. Model
model = keras.models.Sequential()

# 3. Model Block
model.add(keras.layers.Input(shape=(4,)))
model.add(keras.layers.Dense(3, activation='softmax'))

# 4. Compile
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [11]:
# 5. fit
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
5/5 [==============================] - 2s 3ms/step - loss: 4.1102 - accuracy: 0.3333
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 4.0266 - accuracy: 0.3333
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 3.9424 - accuracy: 0.3333
Epoch 4/10
5/5 [==============================] - 0s 3ms/step - loss: 3.8569 - accuracy: 0.3333
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 3.7746 - accuracy: 0.3333
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 3.6928 - accuracy: 0.3333
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 3.6096 - accuracy: 0.3333
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 3.5288 - accuracy: 0.3333
Epoch 9/10
5/5 [==============================] - 0s 3ms/step - loss: 3.4445 - accuracy: 0.3333
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 3.3665 - accuracy: 0.3333


In [13]:
# 6. predict
pred = model.predict(x)[:15].reshape(-1)

In [14]:
print(y[:10])
print(pred[:10])

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
[0.113302   0.00340238 0.8832956  0.12681983 0.0043671  0.86881304
 0.13169514 0.00514291 0.8631619  0.11340324]


## 2. Functional API Style

In [16]:
# 1. Session Clear
keras.backend.clear_session()

# 2. Layer Connection
input_layer = keras.layers.Input(shape=(4,))
output_layer = keras.layers.Dense(3, activation='softmax')(input_layer)

# 3. Model
model = keras.models.Model(inputs=input_layer, outputs=output_layer)

# 4. Compile
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [17]:
# 5. fit
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
5/5 [==============================] - 0s 4ms/step - loss: 3.0604 - accuracy: 0.3333
Epoch 2/10
5/5 [==============================] - 0s 3ms/step - loss: 2.9776 - accuracy: 0.3333
Epoch 3/10
5/5 [==============================] - 0s 4ms/step - loss: 2.8931 - accuracy: 0.3333
Epoch 4/10
5/5 [==============================] - 0s 3ms/step - loss: 2.8133 - accuracy: 0.3333
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 2.7325 - accuracy: 0.3333
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 2.6547 - accuracy: 0.3333
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 2.5819 - accuracy: 0.3333
Epoch 8/10
5/5 [==============================] - 0s 3ms/step - loss: 2.5129 - accuracy: 0.3333
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 2.4419 - accuracy: 0.3333
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 2.3777 - accuracy: 0.3333


In [18]:
# 6. predict
pred = model.predict(x).reshape(-1)

In [19]:
print(y[:15])
print(pred[:15])

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
[0.00909548 0.6902738  0.30063078 0.01342143 0.7054294  0.28114915
 0.01283369 0.6747702  0.31239608 0.01561948 0.67377573 0.31060478
 0.00908021 0.6749057  0.316014  ]
