In [1]:
from sklearn.datasets import load_breast_cancer

In [2]:
cancer = load_breast_cancer()

In [3]:
x = cancer.data
y = cancer.target

In [4]:
x.shape, y.shape

((569, 30), (569,))

In [5]:
# train, valid split
from sklearn.model_selection import train_test_split

x_train, x_valid, y_train, y_valid = train_test_split(x, y, test_size=0.2, random_state=2022)

In [6]:
x_train.shape, y_train.shape

((455, 30), (455,))

In [7]:
# Import
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [13]:
# Modeling : Functional

# 1. Session Clear
keras.backend.clear_session()

# 2. Layer
input_layer = keras.layers.Input(shape=(30, ))
output_layer = keras.layers.Dense(1, activation='sigmoid')(input_layer)

# 3. Model
model = keras.models.Model(inputs=input_layer, outputs=output_layer)

# 4. Compile
model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

In [14]:
# Summary
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 30)]              0         
                                                                 
 dense (Dense)               (None, 1)                 31        
                                                                 
Total params: 31
Trainable params: 31
Non-trainable params: 0
_________________________________________________________________


In [15]:
# 5. fit
model.fit(x_train, y_train, epochs=10, verbose=1)

Epoch 1/10
15/15 [==============================] - 1s 2ms/step - loss: 34.5182 - accuracy: 0.5934
Epoch 2/10
15/15 [==============================] - 0s 2ms/step - loss: 24.6001 - accuracy: 0.3011
Epoch 3/10
15/15 [==============================] - 0s 2ms/step - loss: 21.9277 - accuracy: 0.1363
Epoch 4/10
15/15 [==============================] - 0s 2ms/step - loss: 21.3449 - accuracy: 0.1473
Epoch 5/10
15/15 [==============================] - 0s 2ms/step - loss: 20.6846 - accuracy: 0.1407
Epoch 6/10
15/15 [==============================] - 0s 2ms/step - loss: 19.9843 - accuracy: 0.1451
Epoch 7/10
15/15 [==============================] - 0s 2ms/step - loss: 19.2709 - accuracy: 0.1538
Epoch 8/10
15/15 [==============================] - 0s 2ms/step - loss: 18.5562 - accuracy: 0.1604
Epoch 9/10
15/15 [==============================] - 0s 2ms/step - loss: 17.8545 - accuracy: 0.1670
Epoch 10/10
15/15 [==============================] - 0s 2ms/step - loss: 17.0976 - accuracy: 0.1802


In [16]:
# 6. predict
model.predict(x_valid).reshape(-1)

array([7.69496822e-09, 2.96640592e-05, 1.85040004e-12, 4.36786831e-05,
       5.09304987e-14, 6.02264015e-04, 5.63408403e-14, 1.00000000e+00,
       8.86261016e-02, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       2.72116125e-01, 1.00000000e+00, 7.71201236e-09, 2.64073927e-02,
       1.06475645e-05, 1.11169323e-08, 2.31245023e-04, 7.07253348e-04,
       5.29167533e-01, 3.99428546e-01, 4.91567631e-09, 9.79470432e-01,
       1.34194357e-04, 5.81237067e-08, 1.17076319e-02, 3.02908418e-04,
       3.19325388e-03, 2.27062404e-01, 2.62478454e-04, 6.80422718e-10,
       8.12774897e-01, 8.16415674e-13, 3.59917976e-05, 1.00000000e+00,
       1.12049556e-05, 2.93935001e-01, 1.00000000e+00, 9.84234631e-01,
       5.54641402e-12, 1.00000000e+00, 1.00000000e+00, 5.68178984e-06,
       1.00000000e+00, 1.81392363e-06, 1.00000000e+00, 8.43953032e-08,
       1.00000000e+00, 1.00000000e+00, 9.34708441e-06, 1.00000000e+00,
       9.91879761e-01, 4.35673453e-09, 1.00000000e+00, 1.00000000e+00,
      

## Hidden Layer 추가

In [17]:
# Modeling : Functional

# 1. Session Clear
keras.backend.clear_session()

# 2. Layer
input_layer = keras.layers.Input(shape=(30,))
hidden1 = keras.layers.Dense(32, activation='relu')(input_layer)
hidden2 = keras.layers.Dense(32, activation='relu')(hidden1)
output_layer = keras.layers.Dense(1, activation='sigmoid')(hidden2)

# 3. Model
model = keras.models.Model(inputs=input_layer, outputs=output_layer)

# 4. Compile
model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

In [18]:
# Summary
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 30)]              0         
                                                                 
 dense (Dense)               (None, 32)                992       
                                                                 
 dense_1 (Dense)             (None, 32)                1056      
                                                                 
 dense_2 (Dense)             (None, 1)                 33        
                                                                 
Total params: 2,081
Trainable params: 2,081
Non-trainable params: 0
_________________________________________________________________


In [19]:
# 5. fit
model.fit(x_train, y_train, epochs=10, verbose=1)

Epoch 1/10
15/15 [==============================] - 0s 2ms/step - loss: 6.2684 - accuracy: 0.3714
Epoch 2/10
15/15 [==============================] - 0s 3ms/step - loss: 1.8633 - accuracy: 0.5582
Epoch 3/10
15/15 [==============================] - 0s 2ms/step - loss: 0.8901 - accuracy: 0.7714
Epoch 4/10
15/15 [==============================] - 0s 2ms/step - loss: 0.5113 - accuracy: 0.8264
Epoch 5/10
15/15 [==============================] - 0s 2ms/step - loss: 0.3515 - accuracy: 0.8681
Epoch 6/10
15/15 [==============================] - 0s 2ms/step - loss: 0.6015 - accuracy: 0.8242
Epoch 7/10
15/15 [==============================] - 0s 3ms/step - loss: 0.3606 - accuracy: 0.8813
Epoch 8/10
15/15 [==============================] - 0s 2ms/step - loss: 0.4294 - accuracy: 0.8484
Epoch 9/10
15/15 [==============================] - 0s 2ms/step - loss: 0.3323 - accuracy: 0.9033
Epoch 10/10
15/15 [==============================] - 0s 2ms/step - loss: 0.2929 - accuracy: 0.9099


In [20]:
# 6. predict
y_pred = model.predict(x_valid)

In [21]:
y_valid

array([1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 1])

In [22]:
y_test2 = np.where(y_pred >= 0.5, 1, 0)
y_test2.reshape(-1)

array([1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 1])